import { Sport, VisitType, ProtocolDetail } from '../types';

export const PROTOCOLS: Record<string, ProtocolDetail> = {
  'A1': {
    code: 'A1',
    title: 'Tabella A1',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine"]
  },
  'A2': {
    code: 'A2',
    title: 'Tabella A2',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Neurologico", "EEG (Elettroencefalogramma)"]
  },
  'A2+Ocu': {
    code: 'A2+Ocu',
    title: 'Tabella A2+Ocu',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Neurologico", "EEG (Elettroencefalogramma)", "Esame Oculistico"]
  },
  'A3': {
    code: 'A3',
    title: 'Tabella A3',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Otorinolaringoiatrico", "Audiometria"]
  },
  'A3+Creat': {
    code: 'A3+Creat',
    title: 'Tabella A3+Creat',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Otorinolaringoiatrico", "Audiometria", "Creatinina plasmatica (con calcolo eGFR)"]
  },
  'A4': {
    code: 'A4',
    title: 'Tabella A4',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Neurologico", "EEG (Elettroencefalogramma)", "Esame Otorinolaringoiatrico", "Audiometria"]
  },
  'A4+Ocu': {
    code: 'A4+Ocu',
    title: 'Tabella A4+Ocu',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG a riposo", "Esame Urine", "Esame Neurologico", "EEG (Elettroencefalogramma)", "Esame Otorinolaringoiatrico", "Audiometria", "Esame Oculistico", "Esame Campo Visivo", "Prove Vestibolari"]
  },
  'B1': {
    code: 'B1',
    title: 'Tabella B1',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria"]
  },
  'B1+Ocu': {
    code: 'B1+Ocu',
    title: 'Tabella B1+Ocu',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Oculistico"]
  },
  'B2': {
    code: 'B2',
    title: 'Tabella B2',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Neurologico"]
  },
  'B2+': {
    code: 'B2+',
    title: 'Tabella B2+',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Neurologico", "EEG (Elettroencefalogramma)"]
  },
  'B3': {
    code: 'B3',
    title: 'Tabella B3',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Otorinolaringoiatrico"]
  },
  'B4': {
    code: 'B4',
    title: 'Tabella B4',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Otorinolaringoiatrico", "Audiometria"]
  },
  'B5': {
    code: 'B5',
    title: 'Tabella B5',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Neurologico", "EEG (Elettroencefalogramma)", "Esame Otorinolaringoiatrico", "Audiometria", "Esame Oculistico", "Esame del Fundus Oculi"]
  },
  'B5+PRO': {
    code: 'B5+PRO',
    title: 'Tabella B5+PRO',
    description: '',
    exams: ["Anamnesi", "Esame obiettivo", "Esame acuità visiva", "ECG dopo sforzo (Test Ergometrico / Step Test)", "Esame Urine", "Spirometria", "Esame Neurologico", "EEG (Elettroencefalogramma)", "Esame Otorinolaringoiatrico", "Audiometria", "Esame Oculistico", "Esame del Fundus Oculi", "Ecocardiogramma", "RX Torace", "Risonanza Magnetica Cerebrale", "Emocromo con formula leucocitaria", "Sierologia HBV-HCV"]
  },
  'A1 cip': {
    code: 'A1 cip',
    title: 'A1 cip',
    description: 'Protocollo specifico per atleti con disabilità (CIP).',
    exams: ['Protocollo base', 'Visita oculistica (se ipovedenti)', 'Esami specifici per patologia']
  },
  'A3 cip': {
    code: 'A3 cip',
    title: 'A3 cip',
    description: 'Protocollo specifico per atleti con disabilità (CIP).',
    exams: ['Protocollo base', 'Visita oculistica (se ipovedenti)', 'Esami specifici per patologia']
  },
  'B1 cip': {
    code: 'B1 cip',
    title: 'B1 cip',
    description: 'Protocollo specifico per atleti con disabilità (CIP).',
    exams: ['Protocollo base', 'Visita oculistica (se ipovedenti)', 'Esami specifici per patologia']
  },
  'B2 cip': {
    code: 'B2 cip',
    title: 'B2 cip',
    description: 'Protocollo specifico per atleti con disabilità (CIP).',
    exams: ['Protocollo base', 'Visita oculistica (se ipovedenti)', 'Esami specifici per patologia']
  },
  'Specifica': {
    code: 'Specifica',
    title: 'Specifica',
    description: 'Protocollo specifico per atleti con disabilità (CIP).',
    exams: ['Protocollo base', 'Visita oculistica (se ipovedenti)', 'Esami specifici per patologia']
  },
};

export const PROTOCOL_DESCRIPTIONS: Record<string, string> = {
  'A1': 'ECG a riposo, Esame Urine',
  'A2': 'ECG a riposo, Esame Urine, Esame Neurologico, EEG (Elettroencefalogramma)',
  'A2+Ocu': 'ECG a riposo, Esame Urine, Esame Neurologico, EEG (Elettroencefalogramma), Esame Oculistico',
  'A3': 'ECG a riposo, Esame Urine, Esame Otorinolaringoiatrico, Audiometria',
  'A3+Creat': 'ECG a riposo, Esame Urine, Esame Otorinolaringoiatrico, Audiometria, Creatinina plasmatica (con calcolo eGFR)',
  'A4': 'ECG a riposo, Esame Urine, Esame Neurologico, EEG (Elettroencefalogramma), Esame Otorinolaringoiatrico, Audiometria',
  'A4+Ocu': 'ECG a riposo, Esame Urine, Esame Neurologico, EEG (Elettroencefalogramma), Esame Otorinolaringoiatrico, Audiometria, Esame Oculistico, Esame Campo Visivo, Prove Vestibolari',
  'B1': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria',
  'B1+Ocu': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Oculistico',
  'B2': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Neurologico',
  'B2+': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Neurologico, EEG (Elettroencefalogramma)',
  'B3': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Otorinolaringoiatrico',
  'B4': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Otorinolaringoiatrico, Audiometria',
  'B5': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Neurologico, EEG (Elettroencefalogramma), Esame Otorinolaringoiatrico, Audiometria, Esame Oculistico, Esame del Fundus Oculi',
  'B5+PRO': 'ECG dopo sforzo (Test Ergometrico / Step Test), Esame Urine, Spirometria, Esame Neurologico, EEG (Elettroencefalogramma), Esame Otorinolaringoiatrico, Audiometria, Esame Oculistico, Esame del Fundus Oculi, Ecocardiogramma, RX Torace, Risonanza Magnetica Cerebrale, Emocromo con formula leucocitaria, Sierologia HBV-HCV',
  'A1 cip': 'Protocollo specifico per atleti con disabilità (CIP).',
  'A3 cip': 'Protocollo specifico per atleti con disabilità (CIP).',
  'B1 cip': 'Protocollo specifico per atleti con disabilità (CIP).',
  'B2 cip': 'Protocollo specifico per atleti con disabilità (CIP).',
  'Specifica': 'Protocollo specifico per atleti con disabilità (CIP).',
};

export const SPORTS_LIST: Sport[] = [
  {
    id: 's1',
    name: "Calcio",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'Sportiva',
    seasonPeriod: '01/07 - 30/06',
  },
  {
    id: 's2',
    name: "Calcio a 5 / Calcio a 7 / Calcio a 8",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's3',
    name: "Pallacanestro",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 11, maxAgeM: null,
    minAgeF: 11, maxAgeF: null,
    ageType: 'Solare',
  },
  {
    id: 's4',
    name: "Minibasket",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's5',
    name: "Pallavolo / Beach Volley",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's6',
    name: "Minivolley",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's7',
    name: "Pallamano (Handball)",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's8',
    name: "Minihandball / Beach Handball",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's9',
    name: "Pallanuoto",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 9, maxAgeM: null,
    minAgeF: 9, maxAgeF: null,
    ageType: 'Sportiva',
    seasonPeriod: '01/01 - 31/12',
  },
  {
    id: 's10',
    name: "Rugby",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 12, maxAgeM: 48,
    minAgeF: 12, maxAgeF: 48,
    ageType: 'Solare',
  },
  {
    id: 's11',
    name: "Football Americano (Tackle)",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's12',
    name: "Flag Football",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 10, maxAgeM: null,
    minAgeF: 10, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's13',
    name: "Baseball / Softball",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's14',
    name: "Hockey (Ghiaccio, Pista, Prato, In Line)",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's15',
    name: "Pallapugno (Pallone Elastico)",
    category: "Sport di Squadra",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's16',
    name: "Tamburello",
    category: "Sport di Squadra",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: 10, maxAgeM: null,
    minAgeF: 10, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's17',
    name: "Pugilato PRO (maschi e femmine)",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5+PRO',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Art. 9 Regolamento Sanitario F.P.I."
  },
  {
    id: 's18',
    name: "Pugilato AOB (Aiba Open Boxing)",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Art. 9 Regolamento Sanitario F.P.I."
  },
  {
    id: 's19',
    name: "Pugilato WSB / APB",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5+PRO',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Art. 9 Regolamento Sanitario F.P.I."
  },
  {
    id: 's20',
    name: "Kickboxing Full Contact / K-1 / Muay Thai / Savate (Uomini)",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's21',
    name: "Kickboxing Full Contact / K-1 / Muay Thai / Savate (Donne)",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's22',
    name: "Kickboxing Light Contact / Semi Contact",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's23',
    name: "Amatoriale - Gim boxe / Boxe Competition / Soft Boxe / Light Boxe",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'A1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Circolare F.P.I. 18 Febbraio 2016 - Prot. N. 332/DO"
  },
  {
    id: 's24',
    name: "Judo, Lotta, Karate, Ju-Jitsu, Aikido, Sumo",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's25',
    name: "Wushu Kung Fu - Sanshou",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B5',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's26',
    name: "Wushu Kung Fu Tradizionale / Taolu",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's27',
    name: "Scherma",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's28',
    name: "Kendo",
    category: "Sport di Combattimento e Arti Marziali",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's29',
    name: "Nuoto",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'Sportiva',
    seasonPeriod: '01/01 - 31/12',
  },
  {
    id: 's30',
    name: "Tuffi",
    category: "Sport Acquatici e Subacquei",
    visitType: 'A4',
    validityYears: 1,
    minAgeM: 9, maxAgeM: null,
    minAgeF: 9, maxAgeF: null,
    ageType: 'Sportiva',
    seasonPeriod: '01/01 - 31/12',
  },
  {
    id: 's31',
    name: "Nuoto Sincronizzato",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's32',
    name: "Nuoto per salvamento / Assistente Bagnanti",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's33',
    name: "Nuoto Pinnato",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Nota F.I.P.S.A.S."
  },
  {
    id: 's34',
    name: "Immersione in apnea / Pesca in apnea",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's35',
    name: "Attività subacquee - ARA",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's36',
    name: "Tiro al bersaglio subacqueo",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B4',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's37',
    name: "Hockey / Rugby subacqueo",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's38',
    name: "Safari / Video / Fotografia subacquea",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's39',
    name: "Orientamento Subacqueo",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's40',
    name: "Sci nautico (Classiche, Wakeboard, Surf)",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's41',
    name: "Sci nautico velocità",
    category: "Sport Acquatici e Subacquei",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's42',
    name: "Motonautica",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's43',
    name: "Kitesurf / Windsurf / Surf",
    category: "Sport Acquatici e Subacquei",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's44',
    name: "Automobilismo velocità (Circuito, Rally, Autocross)",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'A2+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Nota Prot. 117 del 18/2/2004 CSAI"
  },
  {
    id: 's45',
    name: "Automobilismo regolarità (Slalom, Trial 4x4)",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'A2+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Nota Prot. 117 del 18/2/2004 CSAI"
  },
  {
    id: 's46',
    name: "Karting",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's47',
    name: "Motociclismo velocità (One Event, PreMoto3)",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's48',
    name: "Motociclismo fuoristrada (Motocross, Enduro, Trial)",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's49',
    name: "Motociclismo Mini Offroad / Miniyoung",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's50',
    name: "Motociclismo E-BIKE",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's51',
    name: "Motoslitte",
    category: "Sport Motociclistici e Automobilistici",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's52',
    name: "Sci alpino (Slalom Speciale, Gigante)",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Norme Tutela Sanitaria FISI - Art. 16"
  },
  {
    id: 's53',
    name: "Sci alpino (Discesa Libera, Super G, Combinata)",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B2+',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Norme Tutela Sanitaria FISI - Art. 16"
  },
  {
    id: 's54',
    name: "Sci di velocità",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's55',
    name: "Sci fondo / Skiroll",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's56',
    name: "Sci Alpinismo",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's57',
    name: "Snowboard / Freestyle / Sci Erba",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's58',
    name: "Biathlon",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B4',
    validityYears: 1,
    minAgeM: 11, maxAgeM: null,
    minAgeF: 11, maxAgeF: null,
    ageType: 'Solare',
    notes: "Norme Tutela Sanitaria FISI - Art. 16"
  },
  {
    id: 's59',
    name: "Combinata nordica / Salto speciale",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B2+',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's60',
    name: "Bob / Skeleton",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Norme Tutela Sanitaria FISI - Art. 16"
  },
  {
    id: 's61',
    name: "Slittino pista artificiale",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "Norme Tutela Sanitaria FISI - Art. 16"
  },
  {
    id: 's62',
    name: "Slittino pista naturale",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'A2',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's63',
    name: "Sport ghiaccio (Velocità, Figura, Danza)",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's64',
    name: "Curling / Stock sport",
    category: "Sport Invernali e Ghiaccio",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's65',
    name: "Atletica Leggera",
    category: "Atletica, Ginnastica e Pesistica",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'Sportiva',
    seasonPeriod: '01/01 - 31/12',
  },
  {
    id: 's66',
    name: "Ginnastica (Artistica, Ritmica, Aerobica, Parkour)",
    category: "Atletica, Ginnastica e Pesistica",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's67',
    name: "Pesistica (Sollevamento Pesi) / Cultura Fisica / Body Building / Crossfit",
    category: "Atletica, Ginnastica e Pesistica",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's68',
    name: "Danza Sportiva / Classica",
    category: "Atletica, Ginnastica e Pesistica",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's69',
    name: "Twirling",
    category: "Atletica, Ginnastica e Pesistica",
    visitType: 'A1',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'Solare',
  },
  {
    id: 's70',
    name: "Tiro a segno - armi ad aria compressa",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's71',
    name: "Tiro a segno - armi a fuoco",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's72',
    name: "Tiro a volo (Piattello)",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A3+Creat',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's73',
    name: "Tiro dinamico sportivo",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's74',
    name: "Caccia (Tiro di campagna, cinotecnica)",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's75',
    name: "Tiro con l\\",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's76',
    name: "Biliardo sportivo",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's77',
    name: "Bowling",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: 9, maxAgeM: null,
    minAgeF: 9, maxAgeF: null,
    ageType: 'Solare',
  },
  {
    id: 's78',
    name: "Bocce (Prove non veloci)",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's79',
    name: "Bocce (Prove veloci)",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's80',
    name: "Golf",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'Solare',
  },
  {
    id: 's81',
    name: "Dama / Scacchi / Bridge",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 2,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's82',
    name: "Giochi e Sport Tradizionali (Escluso tiro alla fune)",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'A1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's83',
    name: "Tiro alla fune / Calcio storico",
    category: "Sport di Precisione, Tiro e Mente",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's84',
    name: "Tennis / Beach Tennis / Paddle",
    category: "Sport di Racchetta",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's85',
    name: "Tennis tavolo",
    category: "Sport di Racchetta",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's86',
    name: "Badminton",
    category: "Sport di Racchetta",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 10, maxAgeM: null,
    minAgeF: 10, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's87',
    name: "Squash",
    category: "Sport di Racchetta",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 11, maxAgeM: null,
    minAgeF: 11, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's88',
    name: "Ciclismo / BMX / Trial",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's89',
    name: "Canottaggio (Vogatore / Timoniere / Sedile Fisso)",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's90',
    name: "Canoa / Kayak / Canoa Polo",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's91',
    name: "Sport equestri (Dressage, Salto, Completo, Volteggio)",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's92',
    name: "Polo",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's93',
    name: "Turismo equestre / Team Penning",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's94',
    name: "Arrampicata sportiva",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's95',
    name: "Orientamento (Corsa di Orientamento)",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's96',
    name: "Rafting / Hydrospeed",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's97',
    name: "Triathlon / Duathlon / Acquathlon",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's98',
    name: "Pentathlon moderno",
    category: "Ciclismo, Canottaggio, Equestri e Outdoor",
    visitType: 'B4',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's99',
    name: "Aerosport / Aeromodellismo",
    category: "Sport Aeronautici",
    visitType: 'A1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's100',
    name: "Paracadutismo sportivo",
    category: "Sport Aeronautici",
    visitType: 'A4',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's101',
    name: "Volo a motore / Volo a vela / Volo da diporto / Parapendio",
    category: "Sport Aeronautici",
    visitType: 'A4+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
    notes: "DPR 207 del 28 Aprile 1993"
  },
  {
    id: 's102',
    name: "Aerostatica / Mongolfiera",
    category: "Sport Aeronautici",
    visitType: 'A4',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's103',
    name: "Arbitro (Calcio)",
    category: "Altri Sport",
    visitType: 'B1+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's104',
    name: "Arbitro (Handball)",
    category: "Altri Sport",
    visitType: 'B1+Ocu',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's105',
    name: "Arbitro (Pallacanestro, Pallavolo, Rugby, Hockey, Atletica)",
    category: "Altri Sport",
    visitType: 'B1',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's106',
    name: "Attività sportiva cinotecnica",
    category: "Altri Sport",
    visitType: 'A3',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'Anagrafica',
  },
  {
    id: 's107',
    name: "Atletica Leggera (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 13, maxAgeM: null,
    minAgeF: 13, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's108',
    name: "Biathlon (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's109',
    name: "Bocce (CIP)",
    category: "Disabilità",
    visitType: 'A1 cip',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's110',
    name: "Calcio (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 15, maxAgeM: null,
    minAgeF: 15, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's111',
    name: "Canoa - Kayak (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 10, maxAgeM: null,
    minAgeF: 10, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's112',
    name: "Canottaggio sedile fisso (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's113',
    name: "Ciclismo (CIP)",
    category: "Disabilità",
    visitType: 'B2 cip',
    validityYears: 1,
    minAgeM: 14, maxAgeM: null,
    minAgeF: 14, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's114',
    name: "Curling (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 14, maxAgeM: null,
    minAgeF: 14, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's115',
    name: "Disciplina non codificata",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's116',
    name: "Discipline Dir-P",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's117',
    name: "Equitazione (CIP)",
    category: "Disabilità",
    visitType: 'B2 cip',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's118',
    name: "Ginnastica (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: 12,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's119',
    name: "Goalball",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 15, maxAgeM: null,
    minAgeF: 15, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's120',
    name: "Golf (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: null, maxAgeM: null,
    minAgeF: null, maxAgeF: null,
    ageType: 'CIP',
  },
  {
    id: 's121',
    name: "Hockey su carrozzina",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 9, maxAgeM: null,
    minAgeF: 9, maxAgeF: null,
    ageType: 'CIP',
  },
  {
    id: 's122',
    name: "Hockey su ghiaccio (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 16, maxAgeM: null,
    minAgeF: 16, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's123',
    name: "Judo - lotta (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 14, maxAgeM: null,
    minAgeF: 14, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's124',
    name: "Minibasket (CIP)",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 6, maxAgeM: 18,
    minAgeF: 6, maxAgeF: 18,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's125',
    name: "Nuoto (CIP)",
    category: "Disabilità",
    visitType: 'B2 cip',
    validityYears: 1,
    minAgeM: 9, maxAgeM: null,
    minAgeF: 9, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's126',
    name: "Pallacanestro (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 14, maxAgeM: null,
    minAgeF: 14, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's127',
    name: "Pallavolo (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's128',
    name: "Scherma (CIP)",
    category: "Disabilità",
    visitType: 'A1 cip',
    validityYears: 1,
    minAgeM: 14, maxAgeM: null,
    minAgeF: 14, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's129',
    name: "Sci alpino (CIP)",
    category: "Disabilità",
    visitType: 'B2 cip',
    validityYears: 1,
    minAgeM: 15, maxAgeM: null,
    minAgeF: 15, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's130',
    name: "Sci nordico (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 16, maxAgeM: null,
    minAgeF: 16, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's131',
    name: "Showdown",
    category: "Disabilità",
    visitType: 'Specifica',
    validityYears: 1,
    minAgeM: 10, maxAgeM: null,
    minAgeF: 10, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's132',
    name: "Tennis (CIP)",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's133',
    name: "Tennis Tavolo (CIP)",
    category: "Disabilità",
    visitType: 'A1 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's134',
    name: "Tiro a segno (CIP)",
    category: "Disabilità",
    visitType: 'A3 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's135',
    name: "Tiro con Arco (CIP)",
    category: "Disabilità",
    visitType: 'A1 cip',
    validityYears: 1,
    minAgeM: 12, maxAgeM: null,
    minAgeF: 12, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's136',
    name: "Torball",
    category: "Disabilità",
    visitType: 'B1 cip',
    validityYears: 1,
    minAgeM: 15, maxAgeM: null,
    minAgeF: 15, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  },
  {
    id: 's137',
    name: "Vela (CIP)",
    category: "Disabilità",
    visitType: 'A1 cip',
    validityYears: 1,
    minAgeM: 8, maxAgeM: null,
    minAgeF: 8, maxAgeF: null,
    ageType: 'CIP',
    seasonPeriod: '01/10 - 30/9',
  }
];