export const PROTOCOLS: Record<string, string[]> = {
  'A1': ['e_ecg', 'e_urine'],
  'A2': ['e_ecg', 'e_urine', 'e_neuro', 'e_eeg'],
  'A2+Ocu': ['e_ecg', 'e_urine', 'e_neuro', 'e_eeg', 'e_ocu'],
  'A3': ['e_ecg', 'e_urine', 'e_oto', 'e_audio'],
  'A3+Creat': ['e_ecg', 'e_urine', 'e_oto', 'e_audio', 'e_creat'],
  'A4': ['e_ecg', 'e_urine', 'e_neuro', 'e_eeg', 'e_oto', 'e_audio'],
  'A4+Ocu': ['e_ecg', 'e_urine', 'e_neuro', 'e_eeg', 'e_oto', 'e_audio', 'e_ocu', 'e_campo', 'e_vestib'],
  'B1': ['e_stress', 'e_urine', 'e_spiro'],
  'B1+Ocu': ['e_stress', 'e_urine', 'e_spiro', 'e_ocu'],
  'B2': ['e_stress', 'e_urine', 'e_spiro', 'e_neuro'],
  'B2+': ['e_stress', 'e_urine', 'e_spiro', 'e_neuro', 'e_eeg'],
  'B3': ['e_stress', 'e_urine', 'e_spiro', 'e_oto'],
  'B4': ['e_stress', 'e_urine', 'e_spiro', 'e_oto', 'e_audio'],
  'B5': ['e_stress', 'e_urine', 'e_spiro', 'e_neuro', 'e_eeg', 'e_oto', 'e_audio', 'e_ocu', 'e_fundus'],
  'B5+PRO': ['e_stress', 'e_urine', 'e_spiro', 'e_neuro', 'e_eeg', 'e_oto', 'e_audio', 'e_ocu', 'e_fundus', 'e_eco', 'e_rx_torace', 'e_rm_cerebr', 'e_emo', 'e_hbv_hcv'],
};

export const PROTOCOL_DESCRIPTIONS: Record<string, string> = {
  'A1': 'Visita clinica, ECG a riposo, Esame urine.',
  'A2': 'A1 + Esame Neurologico + <strong>EEG</strong> (prima visita).',
  'A3': 'A1 + Otorinolaringoiatria + <strong>Audiometria</strong>.',
  'A4': 'A2 + A3 (Completo non-stress).',
  'B1': 'Visita clinica, ECG Sforzo (IRI/Ergometrico), Spirometria, Esame urine.',
  'B2': 'B1 + Esame Neurologico.',
  'B2+': 'B2 + <strong>EEG</strong> (prima visita per sport invernali alto rischio).',
  'B3': 'B1 + Otorinolaringoiatria.',
  'B4': 'B1 + Otorinolaringoiatria + <strong>Audiometria</strong>.',
  'B5': 'B1 + Otorinolaringoiatria + <strong>Audiometria</strong> + Neurologico + <strong>EEG</strong> + Oculistico/Fundus.',
};

export interface SportData {
  name: string;
  protocol: string;
  category: string;
  validity_years: number;
  normativa?: string;
}

export const SPORTS_DATA: SportData[] = [
  { name: 'Calcio', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Calcio a 5 / Calcio a 7 / Calcio a 8', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Pallacanestro', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Minibasket', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Pallavolo / Beach Volley', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Minivolley', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Pallamano (Handball)', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Minihandball / Beach Handball', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Pallanuoto', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Rugby', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Football Americano (Tackle)', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Flag Football', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Baseball / Softball', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Hockey (Ghiaccio, Pista, Prato, In Line)', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Pallapugno (Pallone Elastico)', protocol: 'B1', category: 'Sport di Squadra', validity_years: 1 },
  { name: 'Tamburello', protocol: 'A1', category: 'Sport di Squadra', validity_years: 2 },
  { name: 'Pugilato PRO (maschi e femmine)', protocol: 'B5+PRO', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1, normativa: 'Art. 9 Regolamento Sanitario F.P.I.' },
  { name: 'Pugilato AOB (Aiba Open Boxing)', protocol: 'B5', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1, normativa: 'Art. 9 Regolamento Sanitario F.P.I.' },
  { name: 'Pugilato WSB / APB', protocol: 'B5+PRO', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1, normativa: 'Art. 9 Regolamento Sanitario F.P.I.' },
  { name: 'Kickboxing Full Contact / K-1 / Muay Thai / Savate (Uomini)', protocol: 'B5', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Kickboxing Full Contact / K-1 / Muay Thai / Savate (Donne)', protocol: 'B5', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Kickboxing Light Contact / Semi Contact', protocol: 'B1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Amatoriale - Gim boxe / Boxe Competition / Soft Boxe / Light Boxe', protocol: 'A1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1, normativa: 'Circolare F.P.I. 18 Febbraio 2016 - Prot. N. 332/DO' },
  { name: 'Judo, Lotta, Karate, Ju-Jitsu, Aikido, Sumo', protocol: 'B1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Wushu Kung Fu - Sanshou', protocol: 'B5', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Wushu Kung Fu Tradizionale / Taolu', protocol: 'B1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Scherma', protocol: 'B1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Kendo', protocol: 'B1', category: 'Sport di Combattimento e Arti Marziali', validity_years: 1 },
  { name: 'Nuoto', protocol: 'B1', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Tuffi', protocol: 'A4', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Nuoto Sincronizzato', protocol: 'B1', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Nuoto per salvamento / Assistente Bagnanti', protocol: 'B1+Ocu', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Nuoto Pinnato', protocol: 'B1', category: 'Sport Acquatici e Subacquei', validity_years: 1, normativa: 'Nota F.I.P.S.A.S.' },
  { name: 'Immersione in apnea / Pesca in apnea', protocol: 'B3', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Attività subacquee - ARA', protocol: 'B3', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Tiro al bersaglio subacqueo', protocol: 'B4', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Hockey / Rugby subacqueo', protocol: 'B3', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Safari / Video / Fotografia subacquea', protocol: 'B3', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Orientamento Subacqueo', protocol: 'B3', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Sci nautico (Classiche, Wakeboard, Surf)', protocol: 'B1', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Sci nautico velocità', protocol: 'A2', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Motonautica', protocol: 'A2', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Kitesurf / Windsurf / Surf', protocol: 'B1', category: 'Sport Acquatici e Subacquei', validity_years: 1 },
  { name: 'Automobilismo velocità (Circuito, Rally, Autocross)', protocol: 'A2+Ocu', category: 'Sport Motociclistici e Automobilistici', validity_years: 1, normativa: 'Nota Prot. 117 del 18/2/2004 CSAI' },
  { name: 'Automobilismo regolarità (Slalom, Trial 4x4)', protocol: 'A2+Ocu', category: 'Sport Motociclistici e Automobilistici', validity_years: 1, normativa: 'Nota Prot. 117 del 18/2/2004 CSAI' },
  { name: 'Karting', protocol: 'A2', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Motociclismo velocità (One Event, PreMoto3)', protocol: 'A2', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Motociclismo fuoristrada (Motocross, Enduro, Trial)', protocol: 'B1', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Motociclismo Mini Offroad / Miniyoung', protocol: 'B1', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Motociclismo E-BIKE', protocol: 'B1', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Motoslitte', protocol: 'B1', category: 'Sport Motociclistici e Automobilistici', validity_years: 1 },
  { name: 'Sci alpino (Slalom Speciale, Gigante)', protocol: 'B2', category: 'Sport Invernali e Ghiaccio', validity_years: 1, normativa: 'Norme Tutela Sanitaria FISI - Art. 16' },
  { name: 'Sci alpino (Discesa Libera, Super G, Combinata)', protocol: 'B2+', category: 'Sport Invernali e Ghiaccio', validity_years: 1, normativa: 'Norme Tutela Sanitaria FISI - Art. 16' },
  { name: 'Sci di velocità', protocol: 'A2', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Sci fondo / Skiroll', protocol: 'B1', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Sci Alpinismo', protocol: 'B1', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Snowboard / Freestyle / Sci Erba', protocol: 'B2', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Biathlon', protocol: 'B4', category: 'Sport Invernali e Ghiaccio', validity_years: 1, normativa: 'Norme Tutela Sanitaria FISI - Art. 16' },
  { name: 'Combinata nordica / Salto speciale', protocol: 'B2+', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Bob / Skeleton', protocol: 'A2', category: 'Sport Invernali e Ghiaccio', validity_years: 1, normativa: 'Norme Tutela Sanitaria FISI - Art. 16' },
  { name: 'Slittino pista artificiale', protocol: 'B2', category: 'Sport Invernali e Ghiaccio', validity_years: 1, normativa: 'Norme Tutela Sanitaria FISI - Art. 16' },
  { name: 'Slittino pista naturale', protocol: 'A2', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Sport ghiaccio (Velocità, Figura, Danza)', protocol: 'B1', category: 'Sport Invernali e Ghiaccio', validity_years: 1 },
  { name: 'Curling / Stock sport', protocol: 'A1', category: 'Sport Invernali e Ghiaccio', validity_years: 2 },
  { name: 'Atletica Leggera', protocol: 'B1', category: 'Atletica, Ginnastica e Pesistica', validity_years: 1 },
  { name: 'Ginnastica (Artistica, Ritmica, Aerobica, Parkour)', protocol: 'B1', category: 'Atletica, Ginnastica e Pesistica', validity_years: 1 },
  { name: 'Pesistica (Sollevamento Pesi) / Cultura Fisica / Body Building / Crossfit', protocol: 'B1', category: 'Atletica, Ginnastica e Pesistica', validity_years: 1 },
  { name: 'Danza Sportiva / Classica', protocol: 'B1', category: 'Atletica, Ginnastica e Pesistica', validity_years: 1 },
  { name: 'Twirling', protocol: 'A1', category: 'Atletica, Ginnastica e Pesistica', validity_years: 1 },
  { name: 'Tiro a segno - armi ad aria compressa', protocol: 'A3', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tiro a segno - armi a fuoco', protocol: 'A3', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tiro a volo (Piattello)', protocol: 'A3+Creat', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tiro dinamico sportivo', protocol: 'A3', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Caccia (Tiro di campagna, cinotecnica)', protocol: 'A3', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tiro con l\'arco', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Biliardo sportivo', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Bowling', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Bocce (Prove non veloci)', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Bocce (Prove veloci)', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Golf', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Dama / Scacchi / Bridge', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 2 },
  { name: 'Giochi e Sport Tradizionali (Escluso tiro alla fune)', protocol: 'A1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tiro alla fune / Calcio storico', protocol: 'B1', category: 'Sport di Precisione, Tiro e Mente', validity_years: 1 },
  { name: 'Tennis / Beach Tennis / Paddle', protocol: 'B1', category: 'Sport di Racchetta', validity_years: 1 },
  { name: 'Tennis tavolo', protocol: 'B1', category: 'Sport di Racchetta', validity_years: 1 },
  { name: 'Badminton', protocol: 'B1', category: 'Sport di Racchetta', validity_years: 1 },
  { name: 'Squash', protocol: 'B1', category: 'Sport di Racchetta', validity_years: 1 },
  { name: 'Ciclismo / BMX / Trial', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Canottaggio (Vogatore / Timoniere / Sedile Fisso)', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Canoa / Kayak / Canoa Polo', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Sport equestri (Dressage, Salto, Completo, Volteggio)', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Polo', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Turismo equestre / Team Penning', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Arrampicata sportiva', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Orientamento (Corsa di Orientamento)', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Rafting / Hydrospeed', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Triathlon / Duathlon / Acquathlon', protocol: 'B1', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Pentathlon moderno', protocol: 'B4', category: 'Ciclismo, Canottaggio, Equestri e Outdoor', validity_years: 1 },
  { name: 'Aerosport / Aeromodellismo', protocol: 'A1', category: 'Sport Aeronautici', validity_years: 1 },
  { name: 'Paracadutismo sportivo', protocol: 'A4', category: 'Sport Aeronautici', validity_years: 1 },
  { name: 'Volo a motore / Volo a vela / Volo da diporto / Parapendio', protocol: 'A4+Ocu', category: 'Sport Aeronautici', validity_years: 1, normativa: 'DPR 207 del 28 Aprile 1993' },
  { name: 'Aerostatica / Mongolfiera', protocol: 'A4', category: 'Sport Aeronautici', validity_years: 1 },
  { name: 'Arbitro (Calcio)', protocol: 'B1+Ocu', category: 'Altri Sport', validity_years: 1 },
  { name: 'Arbitro (Handball)', protocol: 'B1+Ocu', category: 'Altri Sport', validity_years: 1 },
  { name: 'Arbitro (Pallacanestro, Pallavolo, Rugby, Hockey, Atletica)', protocol: 'B1', category: 'Altri Sport', validity_years: 1 },
  { name: 'Attività sportiva cinotecnica', protocol: 'A3', category: 'Altri Sport', validity_years: 1 }
];

export const EXAM_LABELS: Record<string, string> = {
  e_ecg: 'ECG a riposo',
  e_stress: 'ECG dopo sforzo (Test Ergometrico / Step Test)',
  e_spiro: 'Spirometria',
  e_neuro: 'Esame Neurologico',
  e_eeg: 'EEG (Elettroencefalogramma)',
  e_oto: 'Esame Otorinolaringoiatrico',
  e_audio: 'Audiometria',
  e_ocu: 'Esame Oculistico',
  e_fundus: 'Esame del Fundus Oculi',
  e_urine: 'Esame Urine',
  e_creat: 'Creatinina plasmatica (con calcolo eGFR)',
  e_uric: 'Uricemia',
  e_gli: 'Glicemia a digiuno',
  e_na: 'Sodio (Na)',
  e_k: 'Potassio (K)',
  e_ca: 'Calcio (Ca)',
  e_coltot: 'Colesterolo totale',
  e_hdl: 'Colesterolo HDL',
  e_ldl: 'Colesterolo LDL (calcolato)',
  e_tg: 'Trigliceridi',
  e_emo: 'Emocromo con formula leucocitaria',
  e_pcr: 'PCR (Proteina C-reattiva)',
  e_ves: 'VES',
  e_trop: 'Troponina cardiaca ad alta sensibilità',
  e_cpkmb: 'CPK-MB',
  e_cpk: 'CPK (Creatinfosfochinasi)',
  e_bnp: 'BNP / NT-proBNP',
  e_tsh: 'TSH',
  e_ft3: 'FT3',
  e_ft4: 'FT4',
  e_ana: 'ANA',
  e_ena: 'ENA',
  e_fr: 'Fattore Reumatoide',
  e_hiv: 'Sierologia HIV',
  e_hbv_hcv: 'Sierologia HBV-HCV',
  e_ebv: 'Sierologia EBV (Mononucleosi)',
  e_lyme: 'Sierologia Borrelia (Lyme)',
  e_eco: 'Ecocardiogramma',
  e_corotc: 'Coro-TC',
  e_rmc: 'RM Cardiaca con mdc',
  e_hecg: 'Holter ECG 24h',
  e_hpa: 'Holter PA 24h',
  e_campo: 'Esame Campo Visivo',
  e_vestib: 'Prove Vestibolari',
  e_vestibolo: 'Esame Vestibolometrico',
  e_rm_cerebr: 'Risonanza Magnetica Cerebrale',
  e_rx_torace: 'RX Torace',
  e_mammo: 'Ecografia Mammaria / Mammografia',
  e_gravid: 'Test di Gravidanza',
  e_pelvica: 'Ecografia Pelvica',
  e_cromo: 'Accertamento Cromosomico',
  e_diab: 'Certificazione diabetologo / endocrinologo',
};
